[package]
name = "pacfilter"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
regex = "1"
ahash = "0.8"

[profile.release]
strip = true
lto = true
